"""indexes added

Revision ID: 84c0e9cc0373
Revises: 8b3e16b8408e
Create Date: 2026-02-11 20:19:26.059029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c0e9cc0373'
down_revision: Union[str, Sequence[str], None] = '8b3e16b8408e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_outbox_created_at', 'outbox', ['created_at'], unique=False)
    op.create_index('ix_outbox_task_id', 'outbox', ['task_id'], unique=False)
    op.create_foreign_key(None, 'outbox', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_status_created_at', 'tasks', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_status_created_at', table_name='tasks')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_created_at', table_name='tasks')
    op.drop_constraint(None, 'outbox', type_='foreignkey')
    op.drop_index('ix_outbox_task_id', table_name='outbox')
    op.drop_index('ix_outbox_created_at', table_name='outbox')
    # ### end Alembic commands ###
